language: node_js
node_js:
  - "10.15.3"
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: public
  on:
    branch: master
